SELECT ENAME, JOB, SAL, NVL(COMM, 0)
FROM EMP
WHERE EMPNO IN (7839, 7566, 7698, 7654);

SELECT ENAME, JOB, SAL, NVL(TO_CHAR(COMM), 'NO DATA FOUND')
FROM EMP
WHERE EMPNO IN (7839, 7566, 7698, 7654);

SELECT ENAME, LENGTH(ENAME), NULLIF(LENGTH(ENAME), 5)
FROM EMP;

SELECT ENAME, LENGTH(ENAME), 
NVL(NULLIF(TO_CHAR(LENGTH(ENAME)), TO_CHAR(5)), 'THE LENGTH IS 5')
FROM EMP;




