SELECT INITCAP('HELLO WORLD!') 
FROM DUAL;

SELECT LENGTH('HELLO WORLD!') 
FROM DUAL;

SELECT ENAME, LENGTH(ENAME) AS LENGHT
FROM EMP;

SELECT SUBSTR('HELLO', 1,4)
FROM DUAL;

SELECT SUBSTR('HELLO', 2)
FROM DUAL;

SELECT LPAD('DAY',6,'-') FROM DUAL;

SELECT RPAD('DAY',6,'-') FROM DUAL;

SELECT LPAD('DAY',8,'+-') FROM DUAL;

SELECT LTRIM('HELLO','H') FROM DUAL;

