SELECT * FROM EMP
WHERE JOB = 'CLERK'
OR JOB = 'SALESMAN';


SELECT ENAME FROM EMP
WHERE JOB != 'MANAGER'
AND JOB != 'SALESMAN'
AND SAL >= 2000;

SELECT * FROM EMP
SELECT * FROM DEPT; -- 20 OR 30 ARE CHICAGO AND DALLAS;

SELECT ENAME, HIREDATE FROM EMP
WHERE DEPTNO != 10; -- It works but if another department number is added the query must be updated

SELECT ENAME, HIREDATE FROM EMP
WHERE DEPTNO IN (20,30);

SELECT ENAME, HIREDATE FROM EMP 
WHERE ENAME IN ('FORD', 'SMITH', 'ALLEN', 'WARD', 'MARTIN');

SELECT ENAME, HIREDATE FROM EMP 
WHERE ENAME NOT IN ('FORD', 'SMITH', 'ALLEN', 'WARD', 'MARTIN');

SELECT * FROM EMP
WHERE HIREDATE BETWEEN '05/01/1981' AND '12/09/1982';

SELECT * FROM EMP
WHERE COMM IS NULL;

SELECT * FROM EMP
WHERE COMM IS NOT NULL;


SELECT * FROM EMP
WHERE COMM IS NULL OR COMM = 0
AND SAL > 1100 AND SAL < 5000
AND SAL <> 3000;


SELECT * FROM EMP 
WHERE JOB = 'SALESMAN'
AND (COMM = 300 OR COMM > 100); 
